version: "3.8"
services:
  postgres:
    container_name: database-api
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    ports:
      - "5534:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: